print("hello to my new repo")
print("new line updated")
print("This is a Dev")
print("Shubham is making this change")
print("Line1")
print("Line2")
print("Changes addded to Main branch - by Shubham")
print("This is a Dev)

print("Push Pull excercise : Chest Shoulder Legs")
print("Sunday Off")
print("shoulder nhi maarunga")